artsy/fresnel

src/Media.tsx

This is a fairly uncommon media query angle, we shouldn't require that end-users define it.

Make `interactions` optional

---

README.md

Clarifies `createMedia` API docs showing how one should export values from the media object to be used throughout app.

Clarify README api

---

README.md

Fix Kitchen Sink example app link typo

---

README.md
examples/ssr-rendering/src/App.tsx
examples/ssr-rendering/src/Media.tsx

The documentation is quite confusing now (and I lost quite a while to understand it completely), since in different examples the `sm` breakpoint has different values, and the closest example (with SSR) to the description of `at`, `greaterThan` and other props has  `sm` === 768, while it's kind of implied that `sm` === 0.
I unified all breakpoints in the documentation and added css rules, which in my opinion clarify the gist rather well.

Documentation corrections.

---

README.md
src/Breakpoints.ts
src/Interactions.ts
src/Media.tsx
src/MediaQueries.ts
src/__test__/Media.test.tsx
src/index.tsx

Currently the output of `.createMediaStyle()` includes all style rules that are possible based on the breakpoint keys. Even if just some are used in a codebase it always results in the same string. While it might not be much it's an overhead that can be avoided by allowing developers to specify a potential subset.
For better referencing the supported breakpoint keys the entries [were defined and exported as an enum](https://github.com/artsy/fresnel/compare/master...Autarc:feat/allow-style-rules-subset?expand=1#diff-c140c1c5c10a63b58a7495d37570cbb1R17).

Allow style rules subsetting

---

README.md
examples/ssr-rendering/src/App.tsx
examples/ssr-rendering/src/Media.tsx

This is a small start to help correct some of the documentation we had around orientation interactions. Specifically prepending `not all and` is an important addition to ensure the negation of other potential orientation matches. 
We'll follow up with #153 to improve the docs further.

Correct orientation interaction docs and add usage examples to ssr demo

---

src/Breakpoints.ts
src/Media.tsx
src/MediaQueries.ts
src/Utils.ts
src/__test__/Media.test.tsx
src/index.tsx

This is a quality of life refactor to ease understanding of what types represent what. It expends generic template names like `B` to be a more descriptive `BreakpointKey`. 
There are a few particular places that deserve special attention which I'll call out in the changes. 
This update expands the generic type names to be self descriptive instead of being single characters. While this change predominately only affects internal types the internal `BreakpointKey` was renamed to `BreakpointConstraint`. Give that that's not documented as part of our external API we haven't listed this release as a breaking change; however, if you use that import you _will_ need to update your references.

Expand generic type names to be more descriptive

---

src/Breakpoints.ts
src/Media.tsx
src/__test__/Breakpoints.test.tsx
src/__test__/Media.test.tsx

This PR introduces a mechanism that prevents children of `Media` from ever rendering if there is no possible way of them rendering - hopefully, a fix for #132. We recently refactored an app to use this library and noticed that the amount of duplicated nodes being rendered was causing performance downside.
Example:
```tsx
<Media at="sm">
<Media at="sm">
<Media at="sm">
</Media>
<Media at="md">
</Media>
</Media>
<Media at="md">
<Media at="sm">
</Media>
<Media at="md">
</Media>
</Media>
</Media>
```
This would result in the server returning 4 of the large `<img />` strings, where we could logically just return 1, given the parent at the root of the tree is an `sm`. The output should ideally be:
```tsx
<div class="fresnel-container fresnel-at-sm">
<div class="fresnel-container fresnel-at-sm"> …
```

Prevent unnecessary nesting of breakpoint nodes (fixes #132)

---

README.md

Closes #174
Open to tweaks on the wording here :)

Add README section for gatsby-plugin-fresnel

---

examples/kitchen-sink/src/App.tsx
src/DynamicResponsive.tsx
src/Media.tsx

Actual React functional component typings are using `SFC`, which are deprecated : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364
Updated them to `Functional Component`

chore: Updated React component typing

---

CHANGELOG.md

Consolidating the v2 changelog updates to address a conflict with
a previously published 2.0.0 version of @artsy/fresnel from over a year
ago.
The 2.0.0 version was released while `auto` was being configured and
until today's major version bump the release had gone unnoticed.
The correct version is now 3.x.x

chore: Remove V2 from Changelog

---

src/Breakpoints.ts
src/Utils.ts

Fixes [issue 208](https://github.com/artsy/fresnel/issues/208) where window widths with fractional pixels cause no content to be rendered when between breakpoints.
I rounded breakpoints to ensure they are always integers, and used a 0.02px delta for the max-width queries. This accounts for the webkit bug where any smaller of a delta gets rounded up ([see here](https://bugs.webkit.org/show_bug.cgi?id=178261)).

Adjust max-width breakpoints to account for fractional pixels

---

.circleci/config.yml
README.md

#FF https://github.com/artsy/README/issues/427

Rename master -> main

---

README.md

Since className is what is used: https://github.com/artsy/fresnel/blob/fa0ff2920a14bad9f33a7f3b687fc3318a5e1fa4/src/Media.tsx#L16

fix typo in Readme: mediaClassNames → className

---

examples/kitchen-sink/README.md
examples/nextjs/next-env.d.ts
examples/nextjs/package.json
examples/nextjs/yarn.lock

Noticed the NextJS example didn't run out of the box and returned this:
```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Please install typescript and @types/react by running:
yarn add --dev typescript @types/react
```
And the command for kitchen-sink should be `start`. Now the examples should run without extra steps!

chore: update examples

---

examples/nextjs/src/components/Articles.tsx
examples/nextjs/src/components/Artists.tsx
examples/nextjs/src/components/Desktop.tsx
examples/nextjs/src/components/Mobile.tsx
examples/nextjs/src/pages/index.tsx
examples/nextjs/src/utils/api.ts
examples/nextjs/src/utils/suspensePromise.ts
examples/ssr-rendering/src/App.tsx
package.json
src/DynamicResponsive.tsx
src/Media.tsx
src/__test__/Media.test.tsx
src/index.tsx
src/suspense/Suspender.tsx
src/suspense/SuspenseWrapper.tsx
src/suspense/suspense.tsx
yarn.lock

Closes https://github.com/artsy/fresnel/pull/289
Closes https://github.com/artsy/fresnel/issues/260
All credit goes to @gurkerl83 and the work he spearheaded in #289 and the investigations in https://github.com/artsy/fresnel/issues/260. Much appreciated! 
This PR integrates that work and updates the examples a bit. One thing that I did do here after experimenting within the NextJS example was integrate the suspense boundary directly into `<Media>` so that we don't have any forced breaking changes in the API and the library behaves as it did before. 
In my testing (and updated in this PR's examples), `<Suspense>` still works as one would expect within the children of `<Media>`, even though `<SuspenseBoundary>` is contained higher-up. I know Dan mentioned that this is a UI thing and that …

feat(react-18): Add official React 18 SSR support

---

README.md
package.json

Removes no longer necessary warning about react 18 incompatibility as that has been fixed here: https://github.com/artsy/fresnel/pull/290

docs(react-18): Update to remove unnecessary warning

---

README.md

Update with note about Next 13 being supported!

docs(readme): update with note about Next 13 + React 18

---

examples/kitchen-sink/src/App.tsx
examples/kitchen-sink/src/client.tsx
examples/kitchen-sink/src/server.tsx
examples/nextjs/src/pages/index.tsx
examples/ssr-rendering/src/App.tsx
package.json
src/Media.tsx
src/Utils.ts

Fixes #260 (hopefully 😅)
Hey folks! I've been following this issue for a while and am hoping to continue using `@artsy/fresnel` on React 18 and beyond. Even with current React 18 support via `disableDynamicMediaQueries`, `@artsy/fresnel` is still the best way I've found to dynamically SSR different markup for different devices.
I recently stumbled on [this gist](https://gist.github.com/OliverJAsh/e9a588e7e907101affe1a7696a25b1fd#file-skiprenderonclient-tsx) which demonstrates a method for avoiding hydration mismatches by using a combination of `useId` and some initial-render logic to clean up the DOM **during hydration**. While the example in the gist isn't realistic because it causes a Flash of Server Rendered Content™, I was intrigued by the idea and set out to see if I could integrate …

React 18 Support: Cleanup DOM during hydration to avoid mismatch

---

src/Media.tsx

Very minior but currently `passedClassName` is optional and will print `undefined`, we can either add a default empty string or massage the class name a bit.

fix: Avoid undefined class name

---

dist/Media.d.ts
dist/MediaQueries.d.ts
dist/Utils.d.ts
package.json
src/Media.tsx
tsconfig.json
yarn.lock

Fixes some more type errors around child props via `any`. Unfortunate, but out of options 🤷 
<details>
<summary>📦 Published PR as canary version: <code>8.0.1--canary.372.4962.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @artsy/fresnel@8.0.1--canary.372.4962.0
yarn add @artsy/fresnel@8.0.1--canary.372.4962.0
```
</details>

fix(types): Fix more type errors
